graphai:
  user: USERNAME
  password: PASSWORD
  url: "https://graphai.epfl.ch/"

mysql:
  client_bin: /usr/local/mysql/bin/mysql
  dump_bin: /usr/local/bin/mysqldump
  server_test: graph_engine_test
  server_prod: graph_prod
  graph_engine_test:
    username: USERNAME
    password: PASSWORD
    host_address: HOST_ADDRESS
    port: PORT
  graph_prod:
    username: USERNAME
    password: PASSWORD
    host_address: HOST_ADDRESS
    port: PORT
  data_path:
    formula: database/formulas/mysql
    export: data/mysql_data_dumps
  schema_test: graphsearch_test
  schema_cache: graph_cache

elasticsearch:
  dump_bin: /usr/local/bin/elasticdump
  server_test: graph_engine_test
  server_prod: graph_prod
  graph_engine_test:
    host: HOST
    port: PORT
    username: USERNAME
    password: PASSWORD
    cert_file: resources/certificates/CERTIFICATE_FILENAME.CRT
  graph_prod:
    host: HOST
    port: PORT
    username: USERNAME
    password: PASSWORD
    cert_file: resources/certificates/CERTIFICATE_FILENAME.CRT
  data_path:
    export: data/elasticsearch_data_exports/
  index_configuration_file: database/config/python/index_config.json

sound:
  player_bin: /usr/bin/vlc
  data_path: resources/sounds/