[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphregistry"
version = "0.1.7"
description = "EPFL Graph Registry"
requires-python = ">=3.10"
dependencies = [
    "uvicorn",
    "fastapi",
    "sqlalchemy",
    "tqdm",
    "loguru",
    "rich",
    "elasticsearch==8.15.1",
    "Levenshtein",
    "requests",
    "termcolor",
    "numpy",
    "pandas",
    "tabulate",
    "pyyaml",
    "pymysql",
    "flatten_dict",
    "dictdiffer",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "openai",
    # Git dependency (PEP 508 syntax)
    "graphdb-client @ git+https://github.com/epflgraph/graphdb-client.git",
    "graphes-client @ git+https://github.com/epflgraph/graphes-client.git",
    "graphai-client @ git+https://github.com/epflgraph/graphai-client.git",
]

[project.scripts]
# CLI entrypoint for the graphregistry package
graphregistry = "graphregistry.entrypoints.cli.main:main"

# Tell setuptools what to package (and what to ignore)
[tool.setuptools.packages.find]
include = ["graphregistry*"]
exclude = [
    "config*",
    "database*",
    "resources*",
    "node_modules*",
    "scripts*",
    "tests*",
]

# Pytest configuration for the project
[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-m 'not integration and not e2e'"
filterwarnings = [
    "ignore::DeprecationWarning",
]
markers = [
    "integration: tests that hit real external systems (DB, APIs, etc.)",
    "e2e: end-to-end tests hitting real systems (DB, CLI, etc.)"
]

[tool.coverage.run]
source = ["graphregistry"]
omit = [
    "*/tests/*",
    "*/test_*",
    "graphregistry/adapters/gateways/graphai/_graphai_client/tests/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
skip_covered = false
show_missing = true