CREATE TABLE IF NOT EXISTS Data_N_Object_N_Object_T_CustomFields (
  from_object_type varchar(32) NOT NULL,
  from_object_id varchar(255) NOT NULL,
  to_object_type varchar(32) NOT NULL,
  to_object_id varchar(255) NOT NULL,
  context varchar(32) NOT NULL,
  field_language enum('en','fr','de','it','n/a') NOT NULL,
  field_name varchar(64) NOT NULL,
  field_value longtext DEFAULT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id),
  KEY field_language (field_language),
  KEY field_name (field_name),
  KEY edge_key (from_object_type,from_object_id,to_object_type,to_object_id),
  KEY context (context)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_CustomFields (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  field_language enum('en','fr','de','it','n/a') NOT NULL,
  field_name varchar(64) NOT NULL,
  field_value longtext DEFAULT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id,field_language,field_name),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY field_language (field_language),
  KEY field_name (field_name),
  KEY object_key (object_type,object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_Embeddings (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  embedding text DEFAULT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY object_type (object_type),
  KEY object_id (object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_FullContent (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  full_content_no_markup_en mediumtext DEFAULT NULL,
  full_content_no_markup_fr mediumtext DEFAULT NULL,
  full_content_no_markup_de varchar(45) DEFAULT NULL,
  full_content_no_markup_it varchar(45) DEFAULT NULL,
  full_content_html_en mediumtext DEFAULT NULL,
  full_content_html_fr mediumtext DEFAULT NULL,
  full_content_html_de varchar(45) DEFAULT NULL,
  full_content_html_it varchar(45) DEFAULT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY object_type (object_type),
  KEY object_id (object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_PageProfile (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  numeric_id_en int(10) unsigned DEFAULT NULL,
  numeric_id_fr int(10) unsigned DEFAULT NULL,
  numeric_id_de int(10) unsigned DEFAULT NULL,
  numeric_id_it int(10) unsigned DEFAULT NULL,
  short_code varchar(255) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  subtype_de varchar(255) DEFAULT NULL,
  subtype_it varchar(255) DEFAULT NULL,
  name_en_is_auto_generated tinyint(1) DEFAULT NULL,
  name_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_en_is_auto_translated tinyint(1) DEFAULT NULL,
  name_en_translated_from char(6) DEFAULT NULL,
  name_en_value mediumtext DEFAULT NULL,
  name_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  name_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  name_fr_translated_from char(6) DEFAULT NULL,
  name_fr_value mediumtext DEFAULT NULL,
  name_de_is_auto_generated tinyint(1) DEFAULT NULL,
  name_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_de_is_auto_translated tinyint(1) DEFAULT NULL,
  name_de_translated_from char(6) DEFAULT NULL,
  name_de_value mediumtext DEFAULT NULL,
  name_it_is_auto_generated tinyint(1) DEFAULT NULL,
  name_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_it_is_auto_translated tinyint(1) DEFAULT NULL,
  name_it_translated_from char(6) DEFAULT NULL,
  name_it_value mediumtext DEFAULT NULL,
  description_short_en_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_en_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_en_translated_from char(6) DEFAULT NULL,
  description_short_en_value mediumtext DEFAULT NULL,
  description_short_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_fr_translated_from char(6) DEFAULT NULL,
  description_short_fr_value mediumtext DEFAULT NULL,
  description_short_de_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_de_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_de_translated_from char(6) DEFAULT NULL,
  description_short_de_value mediumtext DEFAULT NULL,
  description_short_it_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_it_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_it_translated_from char(6) DEFAULT NULL,
  description_short_it_value mediumtext DEFAULT NULL,
  description_medium_en_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_en_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_en_translated_from char(6) DEFAULT NULL,
  description_medium_en_value mediumtext DEFAULT NULL,
  description_medium_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_fr_translated_from char(6) DEFAULT NULL,
  description_medium_fr_value mediumtext DEFAULT NULL,
  description_medium_de_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_de_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_de_translated_from char(6) DEFAULT NULL,
  description_medium_de_value mediumtext DEFAULT NULL,
  description_medium_it_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_it_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_it_translated_from char(6) DEFAULT NULL,
  description_medium_it_value mediumtext DEFAULT NULL,
  description_long_en_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_en_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_en_translated_from char(6) DEFAULT NULL,
  description_long_en_value mediumtext DEFAULT NULL,
  description_long_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_fr_translated_from char(6) DEFAULT NULL,
  description_long_fr_value mediumtext DEFAULT NULL,
  description_long_de_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_de_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_de_translated_from char(6) DEFAULT NULL,
  description_long_de_value mediumtext DEFAULT NULL,
  description_long_it_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_it_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_it_translated_from char(6) DEFAULT NULL,
  description_long_it_value mediumtext DEFAULT NULL,
  external_key_en varchar(255) DEFAULT NULL,
  external_key_fr varchar(255) DEFAULT NULL,
  external_key_de varchar(255) DEFAULT NULL,
  external_key_it varchar(255) DEFAULT NULL,
  external_url_en text DEFAULT NULL,
  external_url_fr text DEFAULT NULL,
  external_url_de text DEFAULT NULL,
  external_url_it text DEFAULT NULL,
  is_visible tinyint(1) NOT NULL DEFAULT 1,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY object_id (object_id),
  KEY subtype_en (subtype_en),
  KEY subtype_fr (subtype_fr),
  KEY subtype_de (subtype_de),
  KEY subtype_it (subtype_it),
  KEY short_code (short_code),
  KEY is_visible (is_visible),
  KEY object_type (object_type),
  KEY numeric_id_fr (numeric_id_fr),
  KEY numeric_id_de (numeric_id_de),
  KEY numeric_id_it (numeric_id_it),
  KEY numeric_id_en (numeric_id_en)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Category_N_Category_T_ChildToParent (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Category_N_Concept_T_AnchorPage (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Category_N_ConceptsCluster_T_ParentToChild (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id),
  KEY idx_l_to_from (to_id,from_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Category_N_OAlexTopic_T_Semantic (
  category_id varchar(255) NOT NULL,
  category_name varchar(255) NOT NULL,
  topic_id varchar(255) NOT NULL,
  topic_name varchar(255) NOT NULL,
  embedding_score float NOT NULL,
  wikipedia_score float NOT NULL,
  score float NOT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (category_id,topic_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Concept_N_Concept_T_Directed (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Concept_N_Concept_T_Embeddings (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  score float NOT NULL,
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Concept_N_Concept_T_Symmetric (
  id varchar(255) NOT NULL,
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  score float NOT NULL,
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Concept_N_Concept_T_Undirected (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  score float NOT NULL,
  normalised_score float DEFAULT NULL,
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_ConceptsCluster_N_Concept_T_ParentToChild (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id),
  KEY idx_c_to_from (to_id,from_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_CuratedArea_N_Category (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_CuratedArea_N_Concept_T_AreaSketcher (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_CuratedArea_N_Concept_T_ConceptDetection (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_CuratedArea_N_CuratedArea_T_ChildToParent (
  from_id varchar(255) NOT NULL,
  to_id varchar(255) NOT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_id,to_id),
  KEY from_id (from_id),
  KEY to_id (to_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Nodes_N_Category (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  id varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  depth int(10) unsigned NOT NULL,
  reference_page_id int(10) unsigned NOT NULL,
  reference_page_key varchar(255) NOT NULL,
  reference_page_url varchar(255) NOT NULL,
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY name (name),
  KEY depth (depth),
  KEY anchor_page_id (reference_page_id),
  KEY anchor_page_key (reference_page_key),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Nodes_N_Concept (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  id varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  is_ontology_category tinyint(1) NOT NULL,
  is_ontology_concept tinyint(1) NOT NULL,
  is_ontology_neighbour tinyint(1) NOT NULL,
  is_noise tinyint(1) NOT NULL DEFAULT 0,
  is_unused tinyint(1) NOT NULL,
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY name (name),
  KEY is_ontology_category (is_ontology_category),
  KEY is_ontology_concept (is_ontology_concept),
  KEY is_ontology_neighbour (is_ontology_neighbour),
  KEY is_unused (is_unused),
  KEY is_noise (is_noise),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Nodes_N_CuratedArea (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  name varchar(255) DEFAULT NULL,
  subtype varchar(255) DEFAULT NULL,
  depth smallint(5) unsigned DEFAULT NULL,
  institution varchar(45) DEFAULT NULL,
  period varchar(255) DEFAULT NULL,
  url text DEFAULT NULL,
  description text DEFAULT NULL,
  date_created date DEFAULT NULL,
  date_terminated date DEFAULT NULL,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY name (name),
  KEY subtype (subtype),
  KEY depth (depth),
  KEY object_type (object_type),
  KEY object_id (object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
