CREATE TABLE IF NOT EXISTS Data_N_Object_T_PageProfile (
  object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') NOT NULL,
  object_id varchar(255) NOT NULL,
  numeric_id_en int(10) unsigned DEFAULT NULL,
  numeric_id_fr int(10) unsigned DEFAULT NULL,
  numeric_id_de int(10) unsigned DEFAULT NULL,
  numeric_id_it int(10) unsigned DEFAULT NULL,
  short_code varchar(255) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  subtype_de varchar(255) DEFAULT NULL,
  subtype_it varchar(255) DEFAULT NULL,
  name_en_is_auto_generated tinyint(4) DEFAULT NULL,
  name_en_is_auto_corrected tinyint(4) DEFAULT NULL,
  name_en_is_auto_translated tinyint(4) DEFAULT NULL,
  name_en_translated_from char(6) DEFAULT NULL,
  name_en_value mediumtext DEFAULT NULL,
  name_fr_is_auto_generated tinyint(4) DEFAULT NULL,
  name_fr_is_auto_corrected tinyint(4) DEFAULT NULL,
  name_fr_is_auto_translated tinyint(4) DEFAULT NULL,
  name_fr_translated_from char(6) DEFAULT NULL,
  name_fr_value mediumtext DEFAULT NULL,
  name_de_is_auto_generated tinyint(4) DEFAULT NULL,
  name_de_is_auto_corrected tinyint(4) DEFAULT NULL,
  name_de_is_auto_translated tinyint(4) DEFAULT NULL,
  name_de_translated_from char(6) DEFAULT NULL,
  name_de_value mediumtext DEFAULT NULL,
  name_it_is_auto_generated tinyint(4) DEFAULT NULL,
  name_it_is_auto_corrected tinyint(4) DEFAULT NULL,
  name_it_is_auto_translated tinyint(4) DEFAULT NULL,
  name_it_translated_from char(6) DEFAULT NULL,
  name_it_value mediumtext DEFAULT NULL,
  description_short_en_is_auto_generated tinyint(4) DEFAULT NULL,
  description_short_en_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_short_en_is_auto_translated tinyint(4) DEFAULT NULL,
  description_short_en_translated_from char(6) DEFAULT NULL,
  description_short_en_value mediumtext DEFAULT NULL,
  description_short_fr_is_auto_generated tinyint(4) DEFAULT NULL,
  description_short_fr_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_short_fr_is_auto_translated tinyint(4) DEFAULT NULL,
  description_short_fr_translated_from char(6) DEFAULT NULL,
  description_short_fr_value mediumtext DEFAULT NULL,
  description_short_de_is_auto_generated tinyint(4) DEFAULT NULL,
  description_short_de_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_short_de_is_auto_translated tinyint(4) DEFAULT NULL,
  description_short_de_translated_from char(6) DEFAULT NULL,
  description_short_de_value mediumtext DEFAULT NULL,
  description_short_it_is_auto_generated tinyint(4) DEFAULT NULL,
  description_short_it_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_short_it_is_auto_translated tinyint(4) DEFAULT NULL,
  description_short_it_translated_from char(6) DEFAULT NULL,
  description_short_it_value mediumtext DEFAULT NULL,
  description_medium_en_is_auto_generated tinyint(4) DEFAULT NULL,
  description_medium_en_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_medium_en_is_auto_translated tinyint(4) DEFAULT NULL,
  description_medium_en_translated_from char(6) DEFAULT NULL,
  description_medium_en_value mediumtext DEFAULT NULL,
  description_medium_fr_is_auto_generated tinyint(4) DEFAULT NULL,
  description_medium_fr_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_medium_fr_is_auto_translated tinyint(4) DEFAULT NULL,
  description_medium_fr_translated_from char(6) DEFAULT NULL,
  description_medium_fr_value mediumtext DEFAULT NULL,
  description_medium_de_is_auto_generated tinyint(4) DEFAULT NULL,
  description_medium_de_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_medium_de_is_auto_translated tinyint(4) DEFAULT NULL,
  description_medium_de_translated_from char(6) DEFAULT NULL,
  description_medium_de_value mediumtext DEFAULT NULL,
  description_medium_it_is_auto_generated tinyint(4) DEFAULT NULL,
  description_medium_it_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_medium_it_is_auto_translated tinyint(4) DEFAULT NULL,
  description_medium_it_translated_from char(6) DEFAULT NULL,
  description_medium_it_value mediumtext DEFAULT NULL,
  description_long_en_is_auto_generated tinyint(4) DEFAULT NULL,
  description_long_en_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_long_en_is_auto_translated tinyint(4) DEFAULT NULL,
  description_long_en_translated_from char(6) DEFAULT NULL,
  description_long_en_value mediumtext DEFAULT NULL,
  description_long_fr_is_auto_generated tinyint(4) DEFAULT NULL,
  description_long_fr_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_long_fr_is_auto_translated tinyint(4) DEFAULT NULL,
  description_long_fr_translated_from char(6) DEFAULT NULL,
  description_long_fr_value mediumtext DEFAULT NULL,
  description_long_de_is_auto_generated tinyint(4) DEFAULT NULL,
  description_long_de_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_long_de_is_auto_translated tinyint(4) DEFAULT NULL,
  description_long_de_translated_from char(6) DEFAULT NULL,
  description_long_de_value mediumtext DEFAULT NULL,
  description_long_it_is_auto_generated tinyint(4) DEFAULT NULL,
  description_long_it_is_auto_corrected tinyint(4) DEFAULT NULL,
  description_long_it_is_auto_translated tinyint(4) DEFAULT NULL,
  description_long_it_translated_from char(6) DEFAULT NULL,
  description_long_it_value mediumtext DEFAULT NULL,
  external_key_en varchar(255) DEFAULT NULL,
  external_key_fr varchar(255) DEFAULT NULL,
  external_key_de varchar(255) DEFAULT NULL,
  external_key_it varchar(255) DEFAULT NULL,
  external_url_en text DEFAULT NULL,
  external_url_fr text DEFAULT NULL,
  external_url_de text DEFAULT NULL,
  external_url_it text DEFAULT NULL,
  is_visible tinyint(4) NOT NULL DEFAULT 1,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (object_type,object_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY is_visible (is_visible),
  KEY numeric_id_en (numeric_id_en),
  KEY numeric_id_fr (numeric_id_fr),
  KEY numeric_id_de (numeric_id_de),
  KEY numeric_id_it (numeric_id_it),
  KEY short_code (short_code),
  KEY subtype_en (subtype_en),
  KEY subtype_fr (subtype_fr),
  KEY subtype_de (subtype_de),
  KEY subtype_it (subtype_it)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
