CREATE TABLE IF NOT EXISTS Data_N_Object_N_Object_T_CustomFields (
  from_object_type varchar(32) NOT NULL,
  from_object_id varchar(255) NOT NULL,
  to_object_type varchar(32) NOT NULL,
  to_object_id varchar(255) NOT NULL,
  context varchar(32) NOT NULL,
  field_language enum('en','fr','de','it','n/a') NOT NULL,
  field_name varchar(64) NOT NULL,
  field_value longtext DEFAULT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_object_type,from_object_id,to_object_type,to_object_id,context,field_language,field_name),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id),
  KEY field_language (field_language),
  KEY field_name (field_name),
  KEY context (context),
  KEY record_deleted (record_deleted),
  KEY edge_key (from_object_type,from_object_id,to_object_type,to_object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_CustomFields (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  field_language enum('en','fr','de','it','n/a') NOT NULL,
  field_name varchar(64) NOT NULL,
  field_value longtext DEFAULT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (object_type,object_id,field_language,field_name),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY field_language (field_language),
  KEY field_name (field_name),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_PageProfile (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  numeric_id_en int(10) unsigned DEFAULT NULL,
  numeric_id_fr int(10) unsigned DEFAULT NULL,
  numeric_id_de int(10) unsigned DEFAULT NULL,
  numeric_id_it int(10) unsigned DEFAULT NULL,
  short_code varchar(255) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  subtype_de varchar(255) DEFAULT NULL,
  subtype_it varchar(255) DEFAULT NULL,
  name_en_is_auto_generated tinyint(1) DEFAULT NULL,
  name_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_en_is_auto_translated tinyint(1) DEFAULT NULL,
  name_en_translated_from char(6) DEFAULT NULL,
  name_en_value mediumtext DEFAULT NULL,
  name_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  name_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  name_fr_translated_from char(6) DEFAULT NULL,
  name_fr_value mediumtext DEFAULT NULL,
  name_de_is_auto_generated tinyint(1) DEFAULT NULL,
  name_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_de_is_auto_translated tinyint(1) DEFAULT NULL,
  name_de_translated_from char(6) DEFAULT NULL,
  name_de_value mediumtext DEFAULT NULL,
  name_it_is_auto_generated tinyint(1) DEFAULT NULL,
  name_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  name_it_is_auto_translated tinyint(1) DEFAULT NULL,
  name_it_translated_from char(6) DEFAULT NULL,
  name_it_value mediumtext DEFAULT NULL,
  description_short_en_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_en_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_en_translated_from char(6) DEFAULT NULL,
  description_short_en_value mediumtext DEFAULT NULL,
  description_short_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_fr_translated_from char(6) DEFAULT NULL,
  description_short_fr_value mediumtext DEFAULT NULL,
  description_short_de_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_de_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_de_translated_from char(6) DEFAULT NULL,
  description_short_de_value mediumtext DEFAULT NULL,
  description_short_it_is_auto_generated tinyint(1) DEFAULT NULL,
  description_short_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_short_it_is_auto_translated tinyint(1) DEFAULT NULL,
  description_short_it_translated_from char(6) DEFAULT NULL,
  description_short_it_value mediumtext DEFAULT NULL,
  description_medium_en_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_en_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_en_translated_from char(6) DEFAULT NULL,
  description_medium_en_value mediumtext DEFAULT NULL,
  description_medium_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_fr_translated_from char(6) DEFAULT NULL,
  description_medium_fr_value mediumtext DEFAULT NULL,
  description_medium_de_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_de_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_de_translated_from char(6) DEFAULT NULL,
  description_medium_de_value mediumtext DEFAULT NULL,
  description_medium_it_is_auto_generated tinyint(1) DEFAULT NULL,
  description_medium_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_medium_it_is_auto_translated tinyint(1) DEFAULT NULL,
  description_medium_it_translated_from char(6) DEFAULT NULL,
  description_medium_it_value mediumtext DEFAULT NULL,
  description_long_en_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_en_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_en_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_en_translated_from char(6) DEFAULT NULL,
  description_long_en_value mediumtext DEFAULT NULL,
  description_long_fr_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_fr_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_fr_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_fr_translated_from char(6) DEFAULT NULL,
  description_long_fr_value mediumtext DEFAULT NULL,
  description_long_de_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_de_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_de_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_de_translated_from char(6) DEFAULT NULL,
  description_long_de_value mediumtext DEFAULT NULL,
  description_long_it_is_auto_generated tinyint(1) DEFAULT NULL,
  description_long_it_is_auto_corrected tinyint(1) DEFAULT NULL,
  description_long_it_is_auto_translated tinyint(1) DEFAULT NULL,
  description_long_it_translated_from char(6) DEFAULT NULL,
  description_long_it_value mediumtext DEFAULT NULL,
  external_key_en varchar(255) DEFAULT NULL,
  external_key_fr varchar(255) DEFAULT NULL,
  external_key_de varchar(255) DEFAULT NULL,
  external_key_it varchar(255) DEFAULT NULL,
  external_url_en text DEFAULT NULL,
  external_url_fr text DEFAULT NULL,
  external_url_de text DEFAULT NULL,
  external_url_it text DEFAULT NULL,
  is_visible tinyint(1) NOT NULL DEFAULT 1,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (object_type,object_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY short_code (short_code),
  KEY subtype_en (subtype_en),
  KEY subtype_fr (subtype_fr),
  KEY subtype_de (subtype_de),
  KEY subtype_it (subtype_it),
  KEY numeric_id_fr (numeric_id_fr),
  KEY numeric_id_de (numeric_id_de),
  KEY numeric_id_it (numeric_id_it),
  KEY is_visible (is_visible),
  KEY numeric_id_en (numeric_id_en),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Concept_T_ConceptDetection (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  concept_id varchar(10) NOT NULL,
  text_source varchar(32) DEFAULT NULL,
  score float NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (object_type,object_id,concept_id,text_source),
  KEY object_id (object_id),
  KEY concept_id (concept_id),
  KEY object_type (object_type),
  KEY text_source (text_source),
  KEY type_src (object_type,text_source),
  KEY idx_cd_object_concept_score (object_type,object_id,concept_id,score),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Concept_T_LLMPostValidated (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  concept_id varchar(10) NOT NULL,
  text_source varchar(32) DEFAULT NULL,
  score float NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY unique_key (object_type,object_id,concept_id,text_source),
  KEY object_id (object_id),
  KEY concept_id (concept_id),
  KEY object_type (object_type),
  KEY text_source (text_source),
  KEY type_src (object_type,text_source),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Concept_T_LLMTags (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  concept_id varchar(10) NOT NULL,
  score float NOT NULL,
  PRIMARY KEY (object_type,object_id,concept_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY concept_id (concept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Concept_T_ManualMapping (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  concept_id varchar(10) NOT NULL,
  concept_name varchar(255) DEFAULT NULL,
  text_source varchar(32) DEFAULT NULL,
  score float NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (object_type,object_id,concept_id,text_source),
  KEY object_id (object_id),
  KEY concept_id (concept_id),
  KEY object_type (object_type),
  KEY text_source (text_source),
  KEY record_deleted (record_deleted),
  KEY concept_name (concept_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Object_T_ChildToParent (
  from_object_type varchar(32) NOT NULL,
  from_object_id varchar(255) NOT NULL,
  to_object_type varchar(32) NOT NULL,
  to_object_id varchar(255) NOT NULL,
  context varchar(32) NOT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_object_type,from_object_id,to_object_type,to_object_id,context),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id),
  KEY context (context),
  KEY idx_cp_reverse_type_id (to_object_type,from_object_type,to_object_id,from_object_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS Nodes_N_Object (
  object_type varchar(32) NOT NULL,
  object_id varchar(255) NOT NULL,
  object_title text DEFAULT NULL,
  text_source varchar(32) DEFAULT NULL,
  raw_text longtext DEFAULT NULL,
  record_created_date datetime DEFAULT current_timestamp(),
  record_updated_date datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  record_deleted tinyint(1) NOT NULL DEFAULT 0,
  row_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (object_type,object_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY record_deleted (record_deleted)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
