CREATE TABLE IF NOT EXISTS Index_D_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  depth mediumint(8) unsigned DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY depth (depth)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Exercise (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Notebook (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  notebook_type varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  repository_id varchar(255) DEFAULT NULL,
  html_document_url mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY notebook_type (notebook_type),
  KEY language (language),
  KEY repository_id (repository_id),
  KEY html_document_url (html_document_url(768))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Category_L_Widget (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  mainly_math_notation tinyint(1) DEFAULT NULL,
  platform_name varchar(255) DEFAULT NULL,
  quiz_type varchar(255) DEFAULT NULL,
  study_level varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY mainly_math_notation (mainly_math_notation),
  KEY platform_name (platform_name),
  KEY quiz_type (quiz_type),
  KEY study_level (study_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Exercise (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Notebook (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  notebook_type varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  repository_id varchar(255) DEFAULT NULL,
  html_document_url mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY notebook_type (notebook_type),
  KEY language (language),
  KEY repository_id (repository_id),
  KEY html_document_url (html_document_url(768))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Concept_L_Widget (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  mainly_math_notation tinyint(1) DEFAULT NULL,
  platform_name varchar(255) DEFAULT NULL,
  quiz_type varchar(255) DEFAULT NULL,
  study_level varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY mainly_math_notation (mainly_math_notation),
  KEY platform_name (platform_name),
  KEY quiz_type (quiz_type),
  KEY study_level (study_level)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course_L_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course_L_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course_L_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Course_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Exercise_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Exercise_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture_L_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture_L_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture_L_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Lecture_L_Widget (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  mainly_math_notation tinyint(1) DEFAULT NULL,
  platform_name varchar(255) DEFAULT NULL,
  quiz_type varchar(255) DEFAULT NULL,
  study_level varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY mainly_math_notation (mainly_math_notation),
  KEY platform_name (platform_name),
  KEY quiz_type (quiz_type),
  KEY study_level (study_level)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC_L_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC_L_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC_L_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_MOOC_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Notebook (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  notebook_type varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  repository_id varchar(255) DEFAULT NULL,
  html_document_url mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY notebook_type (notebook_type),
  KEY language (language),
  KEY repository_id (repository_id),
  KEY html_document_url (html_document_url(768))
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Notebook_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Notebook_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Notebook_L_Notebook (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  notebook_type varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  repository_id varchar(255) DEFAULT NULL,
  html_document_url mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY notebook_type (notebook_type),
  KEY language (language),
  KEY repository_id (repository_id),
  KEY html_document_url (html_document_url(768))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Notebook_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  is_at_epfl tinyint(1) DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY is_at_epfl (is_at_epfl),
  KEY gender (gender)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Course (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  latest_academic_year varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY latest_academic_year (latest_academic_year)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_MOOC (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  domain varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  level varchar(255) DEFAULT NULL,
  platform varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY domain (domain),
  KEY language (language),
  KEY level (level),
  KEY platform (platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Notebook (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  notebook_type varchar(255) DEFAULT NULL,
  language varchar(255) DEFAULT NULL,
  repository_id varchar(255) DEFAULT NULL,
  html_document_url mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY notebook_type (notebook_type),
  KEY language (language),
  KEY repository_id (repository_id),
  KEY html_document_url (html_document_url(768))
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Person_L_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  year mediumint(8) unsigned DEFAULT NULL,
  published_in mediumtext DEFAULT NULL,
  publisher varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY year (year),
  KEY published_in (published_in(768)),
  KEY publisher (publisher)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication_L_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication_L_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Publication_L_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup_L_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup_L_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Startup_L_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  is_active_unit tinyint(1) DEFAULT NULL,
  is_research_unit tinyint(1) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY is_active_unit (is_active_unit),
  KEY is_research_unit (is_research_unit)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit_L_Person (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit_L_Publication (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit_L_Startup (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Unit_L_Unit (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Widget (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  degree_score float NOT NULL,
  short_code varchar(32) DEFAULT NULL,
  subtype_en varchar(255) DEFAULT NULL,
  subtype_fr varchar(255) DEFAULT NULL,
  name_en mediumtext DEFAULT NULL,
  name_fr mediumtext DEFAULT NULL,
  short_description_en mediumtext DEFAULT NULL,
  short_description_fr mediumtext DEFAULT NULL,
  long_description_en longtext DEFAULT NULL,
  long_description_fr longtext DEFAULT NULL,
  mainly_math_notation tinyint(1) DEFAULT NULL,
  platform_name varchar(255) DEFAULT NULL,
  quiz_type varchar(255) DEFAULT NULL,
  study_level varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY mainly_math_notation (mainly_math_notation),
  KEY platform_name (platform_name),
  KEY quiz_type (quiz_type),
  KEY study_level (study_level)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Widget_L_Category (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Widget_L_Concept (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Widget_L_Lecture (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Index_D_Widget_L_Widget (
  doc_type varchar(64) NOT NULL,
  doc_id varchar(255) NOT NULL,
  link_type varchar(64) NOT NULL,
  link_subtype enum('Parent-to-Child','Child-to-Parent','Semantic') NOT NULL,
  link_id varchar(255) NOT NULL,
  link_rank int(10) unsigned NOT NULL,
  link_name_en mediumtext DEFAULT NULL,
  link_name_fr mediumtext DEFAULT NULL,
  link_short_description_en mediumtext DEFAULT NULL,
  link_short_description_fr mediumtext DEFAULT NULL,
  mainly_math_notation tinyint(1) DEFAULT NULL,
  platform_name varchar(255) DEFAULT NULL,
  quiz_type varchar(255) DEFAULT NULL,
  study_level varchar(255) DEFAULT NULL,
  row_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY uid (doc_type,doc_id,link_type,link_subtype,link_id),
  KEY doc_type (doc_type),
  KEY doc_id (doc_id),
  KEY link_type (link_type),
  KEY link_subtype (link_subtype),
  KEY link_id (link_id),
  KEY mainly_math_notation (mainly_math_notation),
  KEY platform_name (platform_name),
  KEY quiz_type (quiz_type),
  KEY study_level (study_level)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
