CREATE TABLE `Data_N_Object_T_PageProfile` (
  `institution_id` varchar(6) NOT NULL,
  `object_type` varchar(32) NOT NULL,
  `object_id` varchar(255) NOT NULL,
  `numeric_id_en` int(10) unsigned DEFAULT NULL,
  `numeric_id_fr` int(10) unsigned DEFAULT NULL,
  `numeric_id_de` int(10) unsigned DEFAULT NULL,
  `numeric_id_it` int(10) unsigned DEFAULT NULL,
  `short_code` varchar(255) DEFAULT NULL,
  `subtype_en` varchar(255) DEFAULT NULL,
  `subtype_fr` varchar(255) DEFAULT NULL,
  `subtype_de` varchar(255) DEFAULT NULL,
  `subtype_it` varchar(255) DEFAULT NULL,
  `name_en_is_auto_generated` tinyint(1) DEFAULT NULL,
  `name_en_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `name_en_is_auto_translated` tinyint(1) DEFAULT NULL,
  `name_en_translated_from` char(6) DEFAULT NULL,
  `name_en_value` mediumtext DEFAULT NULL,
  `name_fr_is_auto_generated` tinyint(1) DEFAULT NULL,
  `name_fr_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `name_fr_is_auto_translated` tinyint(1) DEFAULT NULL,
  `name_fr_translated_from` char(6) DEFAULT NULL,
  `name_fr_value` mediumtext DEFAULT NULL,
  `name_de_is_auto_generated` tinyint(1) DEFAULT NULL,
  `name_de_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `name_de_is_auto_translated` tinyint(1) DEFAULT NULL,
  `name_de_translated_from` char(6) DEFAULT NULL,
  `name_de_value` mediumtext DEFAULT NULL,
  `name_it_is_auto_generated` tinyint(1) DEFAULT NULL,
  `name_it_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `name_it_is_auto_translated` tinyint(1) DEFAULT NULL,
  `name_it_translated_from` char(6) DEFAULT NULL,
  `name_it_value` mediumtext DEFAULT NULL,
  `description_short_en_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_short_en_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_short_en_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_short_en_translated_from` char(6) DEFAULT NULL,
  `description_short_en_value` mediumtext DEFAULT NULL,
  `description_short_fr_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_short_fr_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_short_fr_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_short_fr_translated_from` char(6) DEFAULT NULL,
  `description_short_fr_value` mediumtext DEFAULT NULL,
  `description_short_de_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_short_de_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_short_de_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_short_de_translated_from` char(6) DEFAULT NULL,
  `description_short_de_value` mediumtext DEFAULT NULL,
  `description_short_it_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_short_it_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_short_it_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_short_it_translated_from` char(6) DEFAULT NULL,
  `description_short_it_value` mediumtext DEFAULT NULL,
  `description_medium_en_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_medium_en_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_medium_en_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_medium_en_translated_from` char(6) DEFAULT NULL,
  `description_medium_en_value` mediumtext DEFAULT NULL,
  `description_medium_fr_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_medium_fr_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_medium_fr_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_medium_fr_translated_from` char(6) DEFAULT NULL,
  `description_medium_fr_value` mediumtext DEFAULT NULL,
  `description_medium_de_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_medium_de_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_medium_de_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_medium_de_translated_from` char(6) DEFAULT NULL,
  `description_medium_de_value` mediumtext DEFAULT NULL,
  `description_medium_it_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_medium_it_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_medium_it_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_medium_it_translated_from` char(6) DEFAULT NULL,
  `description_medium_it_value` mediumtext DEFAULT NULL,
  `description_long_en_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_long_en_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_long_en_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_long_en_translated_from` char(6) DEFAULT NULL,
  `description_long_en_value` mediumtext DEFAULT NULL,
  `description_long_fr_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_long_fr_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_long_fr_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_long_fr_translated_from` char(6) DEFAULT NULL,
  `description_long_fr_value` mediumtext DEFAULT NULL,
  `description_long_de_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_long_de_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_long_de_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_long_de_translated_from` char(6) DEFAULT NULL,
  `description_long_de_value` mediumtext DEFAULT NULL,
  `description_long_it_is_auto_generated` tinyint(1) DEFAULT NULL,
  `description_long_it_is_auto_corrected` tinyint(1) DEFAULT NULL,
  `description_long_it_is_auto_translated` tinyint(1) DEFAULT NULL,
  `description_long_it_translated_from` char(6) DEFAULT NULL,
  `description_long_it_value` mediumtext DEFAULT NULL,
  `external_key_en` varchar(255) DEFAULT NULL,
  `external_key_fr` varchar(255) DEFAULT NULL,
  `external_key_de` varchar(255) DEFAULT NULL,
  `external_key_it` varchar(255) DEFAULT NULL,
  `external_url_en` text DEFAULT NULL,
  `external_url_fr` text DEFAULT NULL,
  `external_url_de` text DEFAULT NULL,
  `external_url_it` text DEFAULT NULL,
  `is_visible` tinyint(1) NOT NULL DEFAULT 1,
  `record_created_date` datetime DEFAULT current_timestamp(),
  `record_updated_date` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `record_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `row_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`row_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
