
CREATE TABLE IF NOT EXISTS Operations_N_Object_N_Object_T_FieldsChanged (
  from_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  to_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  context varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  checksum_current char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  checksum_previous char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  has_changed tinyint DEFAULT '0',
  last_date_cached date DEFAULT NULL,
  has_expired tinyint DEFAULT '0',
  to_process tinyint NOT NULL DEFAULT '0',
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY object_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id),
  KEY from_institution_id (from_institution_id),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_institution_id (to_institution_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id),
  KEY fields_checksum_current (checksum_current),
  KEY fields_checksum_previous (checksum_previous),
  KEY fields_have_changed (has_changed),
  KEY edge_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id),
  KEY full_type (from_institution_id,from_object_type,to_institution_id,to_object_type),
  KEY from_full_type (from_institution_id,from_object_type),
  KEY from_full_id (from_institution_id,from_object_type,from_object_id),
  KEY to_full_type (to_institution_id,to_object_type),
  KEY to_full_id (to_institution_id,to_object_type,to_object_id),
  KEY last_date_calculated (last_date_cached),
  KEY has_expired (has_expired),
  KEY to_process (to_process)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Operations_N_Object_N_Object_T_TypeFlags (
  from_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  flag_type enum('fields','scores') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_process tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (from_institution_id,from_object_type,to_institution_id,to_object_type,flag_type),
  KEY from_institution_id (from_institution_id),
  KEY from_object_type (from_object_type),
  KEY to_institution_id (to_institution_id),
  KEY to_object_type (to_object_type),
  KEY to_process (to_process),
  KEY flag_type (flag_type),
  KEY full_type (from_institution_id,from_object_type,to_institution_id,to_object_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Operations_N_Object_T_FieldsChanged (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  checksum_current char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  checksum_previous char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  has_changed tinyint DEFAULT '0',
  last_date_cached date DEFAULT NULL,
  has_expired tinyint DEFAULT '0',
  to_process tinyint NOT NULL DEFAULT '0',
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY object_key (institution_id,object_type,object_id),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY fields_checksum_current (checksum_current),
  KEY fields_checksum_previous (checksum_previous),
  KEY fields_have_changed (has_changed),
  KEY last_date_calculated (last_date_cached),
  KEY has_expired (has_expired),
  KEY to_process (to_process)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Operations_N_Object_T_ScoresExpired (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  last_date_cached date DEFAULT NULL,
  has_expired tinyint DEFAULT NULL,
  to_process tinyint NOT NULL DEFAULT '0',
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY object_key (institution_id,object_type,object_id),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY last_date_cached (last_date_cached),
  KEY has_expired (has_expired),
  KEY to_process (to_process)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Operations_N_Object_T_TypeFlags (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Curated area','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Slide','Specialisation','Startup','Strategic area','StudyPlan','Transcript','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  flag_type enum('fields','scores') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_process tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (institution_id,object_type,flag_type),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY to_process (to_process),
  KEY flag_type (flag_type),
  KEY full_type (institution_id,object_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
