
CREATE TABLE IF NOT EXISTS Data_N_Object_N_Object_T_CustomFields (
  from_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  to_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  context enum('accreditation','affiliation','authorship','coursebook','teacher','founder') COLLATE utf8mb4_unicode_ci NOT NULL,
  field_language enum('en','fr','de','it','n/a') COLLATE utf8mb4_unicode_ci NOT NULL,
  field_name varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  field_value text COLLATE utf8mb4_unicode_ci NOT NULL,
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id,field_language,field_name,context),
  KEY from_institution_id (from_institution_id),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_institution_id (to_institution_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id),
  KEY field_language (field_language),
  KEY field_name (field_name),
  KEY edge_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_CustomFields (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  field_language enum('en','fr','de','it','n/a') COLLATE utf8mb4_unicode_ci NOT NULL,
  field_name varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  field_value text COLLATE utf8mb4_unicode_ci NOT NULL,
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (institution_id,object_type,object_id,field_language,field_name),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY field_language (field_language),
  KEY field_name (field_name),
  KEY object_key (institution_id,object_type,object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Data_N_Object_T_PageProfile (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  numeric_id_en int unsigned DEFAULT NULL,
  numeric_id_fr int unsigned DEFAULT NULL,
  numeric_id_de int unsigned DEFAULT NULL,
  numeric_id_it int unsigned DEFAULT NULL,
  short_code varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  subtype_en varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  subtype_fr varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  subtype_de varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  subtype_it varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_en_is_auto_generated tinyint DEFAULT NULL,
  name_en_is_auto_corrected tinyint DEFAULT NULL,
  name_en_is_auto_translated tinyint DEFAULT NULL,
  name_en_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_en_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  name_fr_is_auto_generated tinyint DEFAULT NULL,
  name_fr_is_auto_corrected tinyint DEFAULT NULL,
  name_fr_is_auto_translated tinyint DEFAULT NULL,
  name_fr_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_fr_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  name_de_is_auto_generated tinyint DEFAULT NULL,
  name_de_is_auto_corrected tinyint DEFAULT NULL,
  name_de_is_auto_translated tinyint DEFAULT NULL,
  name_de_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_de_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  name_it_is_auto_generated tinyint DEFAULT NULL,
  name_it_is_auto_corrected tinyint DEFAULT NULL,
  name_it_is_auto_translated tinyint DEFAULT NULL,
  name_it_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_it_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_short_en_is_auto_generated tinyint DEFAULT NULL,
  description_short_en_is_auto_corrected tinyint DEFAULT NULL,
  description_short_en_is_auto_translated tinyint DEFAULT NULL,
  description_short_en_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_short_en_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_short_fr_is_auto_generated tinyint DEFAULT NULL,
  description_short_fr_is_auto_corrected tinyint DEFAULT NULL,
  description_short_fr_is_auto_translated tinyint DEFAULT NULL,
  description_short_fr_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_short_fr_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_short_de_is_auto_generated tinyint DEFAULT NULL,
  description_short_de_is_auto_corrected tinyint DEFAULT NULL,
  description_short_de_is_auto_translated tinyint DEFAULT NULL,
  description_short_de_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_short_de_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_short_it_is_auto_generated tinyint DEFAULT NULL,
  description_short_it_is_auto_corrected tinyint DEFAULT NULL,
  description_short_it_is_auto_translated tinyint DEFAULT NULL,
  description_short_it_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_short_it_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_medium_en_is_auto_generated tinyint DEFAULT NULL,
  description_medium_en_is_auto_corrected tinyint DEFAULT NULL,
  description_medium_en_is_auto_translated tinyint DEFAULT NULL,
  description_medium_en_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_medium_en_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_medium_fr_is_auto_generated tinyint DEFAULT NULL,
  description_medium_fr_is_auto_corrected tinyint DEFAULT NULL,
  description_medium_fr_is_auto_translated tinyint DEFAULT NULL,
  description_medium_fr_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_medium_fr_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_medium_de_is_auto_generated tinyint DEFAULT NULL,
  description_medium_de_is_auto_corrected tinyint DEFAULT NULL,
  description_medium_de_is_auto_translated tinyint DEFAULT NULL,
  description_medium_de_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_medium_de_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_medium_it_is_auto_generated tinyint DEFAULT NULL,
  description_medium_it_is_auto_corrected tinyint DEFAULT NULL,
  description_medium_it_is_auto_translated tinyint DEFAULT NULL,
  description_medium_it_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_medium_it_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_long_en_is_auto_generated tinyint DEFAULT NULL,
  description_long_en_is_auto_corrected tinyint DEFAULT NULL,
  description_long_en_is_auto_translated tinyint DEFAULT NULL,
  description_long_en_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_long_en_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_long_fr_is_auto_generated tinyint DEFAULT NULL,
  description_long_fr_is_auto_corrected tinyint DEFAULT NULL,
  description_long_fr_is_auto_translated tinyint DEFAULT NULL,
  description_long_fr_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_long_fr_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_long_de_is_auto_generated tinyint DEFAULT NULL,
  description_long_de_is_auto_corrected tinyint DEFAULT NULL,
  description_long_de_is_auto_translated tinyint DEFAULT NULL,
  description_long_de_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_long_de_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  description_long_it_is_auto_generated tinyint DEFAULT NULL,
  description_long_it_is_auto_corrected tinyint DEFAULT NULL,
  description_long_it_is_auto_translated tinyint DEFAULT NULL,
  description_long_it_translated_from char(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  description_long_it_value mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  external_key_en varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  external_key_fr varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  external_key_de varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  external_key_it varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  external_url_en text COLLATE utf8mb4_unicode_ci,
  external_url_fr text COLLATE utf8mb4_unicode_ci,
  external_url_de text COLLATE utf8mb4_unicode_ci,
  external_url_it text COLLATE utf8mb4_unicode_ci,
  is_visible tinyint NOT NULL DEFAULT '0',
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY object_key (institution_id,object_type,object_id),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY short_code (short_code),
  KEY numeric_id_fr (numeric_id_fr),
  KEY numeric_id_de (numeric_id_de),
  KEY numeric_id_it (numeric_id_it),
  KEY subtype_en (subtype_en),
  KEY subtype_fr (subtype_fr),
  KEY subtype_de (subtype_de),
  KEY subtype_it (subtype_it),
  KEY is_visible (is_visible),
  KEY numeric_id_en (numeric_id_en)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Concept_T_ConceptDetection (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  concept_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  text_source enum('startup website','course page description','abstract','quiz description','biography','unit website') COLLATE utf8mb4_unicode_ci NOT NULL,
  score float NOT NULL,
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (institution_id,object_type,object_id,concept_id,text_source),
  KEY object_id (object_id),
  KEY concept_id (concept_id),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY text_source (text_source),
  KEY obj_ccp (institution_id,object_id,concept_id),
  KEY type_src (object_type,text_source)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Concept_T_ManualMapping (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  concept_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  concept_name varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  text_source enum('startup website','course page description','unit website','exercise') COLLATE utf8mb4_unicode_ci NOT NULL,
  score float NOT NULL DEFAULT '1',
  record_created_date datetime DEFAULT NULL,
  record_updated_date datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (institution_id,object_type,object_id,concept_id,text_source),
  KEY object_id (object_id),
  KEY concept_id (concept_id),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY text_source (text_source)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Object_T_ChildToParent (
  from_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  to_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  context enum('accreditation','affiliation','authorship','coursebook','teacher','founder') COLLATE utf8mb4_unicode_ci NOT NULL,
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id,context),
  KEY from_institution_id (from_institution_id),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_institution_id (to_institution_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id),
  KEY context (context),
  KEY edge_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id),
  KEY edge_from_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,context),
  KEY edge_to_key (from_institution_id,from_object_type,to_institution_id,to_object_type,to_object_id,context)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Edges_N_Object_N_Object_T_IdMap (
  from_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  to_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_institution_id,from_object_type,from_object_id,to_institution_id,to_object_type,to_object_id),
  KEY from_institution_id (from_institution_id),
  KEY from_object_type (from_object_type),
  KEY from_object_id (from_object_id),
  KEY to_institution_id (to_institution_id),
  KEY to_object_type (to_object_type),
  KEY to_object_id (to_object_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Mapping_N_Field_N_Field (
  from_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  from_field_name varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  from_field_value varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  to_institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  to_field_name varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  to_field_value varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  context varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY unique_key (from_institution_id,from_object_type,from_field_name,from_field_value,to_institution_id,to_object_type,to_field_name,to_field_value,context),
  KEY from_institution_id (from_institution_id),
  KEY from_object_type (from_object_type),
  KEY from_field_name (from_field_name),
  KEY to_institution_id (to_institution_id),
  KEY to_object_type (to_object_type),
  KEY to_field_name (to_field_name),
  KEY context (context)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Nodes_N_Object (
  institution_id enum('Ont','EPFL','ETHZ','PSI','Empa','Eawag','WSL') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_type enum('Category','Chart','Concept','Course','Dashboard','Exercise','External person','Hardware','Historical figure','Lecture','Learning module','MOOC','News','Notebook','Person','Publication','Specialisation','Startup','Strategic area','StudyPlan','Unit','Widget') COLLATE utf8mb4_unicode_ci NOT NULL,
  object_id varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  object_title text COLLATE utf8mb4_unicode_ci,
  text_source enum('startup website','course page description','abstract','quiz description','biography','unit website') COLLATE utf8mb4_unicode_ci NOT NULL,
  raw_text longtext COLLATE utf8mb4_unicode_ci,
  record_created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_updated_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  row_id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (row_id),
  UNIQUE KEY row_id (row_id),
  UNIQUE KEY object_key (institution_id,object_type,object_id),
  KEY institution_id (institution_id),
  KEY object_type (object_type),
  KEY object_id (object_id),
  KEY object_type_id (object_type,object_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
